[package]
name = "godel-helper-bot"
version = "0.1.0"
authors = ["nolik"]
edition = "2018"

[dependencies]
teloxide = { version = "0.5.3", features = ["auto-send", "macros"] }
log = "0.4.8"
pretty_env_logger = "0.4.0"
tokio = { version = "1.10.1", features = ["rt-multi-thread", "macros"] }